apiVersion: apps/v1
kind: Deployment
metadata:
  name: repository-ws-backend
  namespace: kube-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repository-app-ws-backend
      tier: backend
  template:
    metadata:
      labels:
        app: repository-app-ws-backend
        tier: backend
    spec:
      containers:
        - name: repository-ws-backend
          image: https://index.docker.io/v1/consoleadm2020/repository-tools-public:project-backend_f26f7a32
          env:
            - name: PROFILE
              value: dev
          resources:
            limits:
              memory: "512Mi"
      imagePullSecrets:
        - name: secretregistry
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: repository-ws-backend
  namespace: kube-public
spec:
  selector:
    app: repository-app-ws-backend
    tier: backend
  ports:
    - name: http
      protocol: "TCP"
      port: 8085
      targetPort: 8085
  type: Cluster
