AWSTemplateFormatVersion: '2010-09-09'
Description: Template S3 Bucket
Parameters:
  ResourceName:
    Type: String
    Description: The name of the S3 Bucket to create
  BlockPublicAcls:
    Type: Boolean
    Default: true
    Description: Block public access control lists (ACLs)
  BlockPublicPolicy:
    Type: Boolean
    Default: true
    Description: Block public bucket policies for this bucket
  IgnorePublicAcls:
    Type: Boolean
    Default: true
    Description: Ignore public ACLs for this bucket
  RestrictPublicBuckets:
    Type: Boolean
    Default: true
    Description: Restrict public bucket policies for this bucket
  Versioning:
    Type: "String"
    Default: "Suspended"
    Description: "Versioning [Enabled,Suspended]"
  ParamTagEnv:
    Type: "String"
    Default: ""
    Description: "Tag of Environment [DEV,UAT,PRD]"
  ParamTagProject:
    Type: "String"
    Default: ""
    Description: "Tag name of Project"
  ParamTagCostCenter:
    Type: "String"
    Default: ""
    Description: "Tag cost center"
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ResourceName}"
      AccessControl: Private
      VersioningConfiguration: 
        Status: !Sub "${Versioning}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: !Sub "${BlockPublicAcls}"
        BlockPublicPolicy: !Sub "${BlockPublicPolicy}"
        IgnorePublicAcls: !Sub "${IgnorePublicAcls}"
        RestrictPublicBuckets: !Sub "${RestrictPublicBuckets}"
      Tags:
        - Key: PROYECTO
          Value: !Sub "${ParamTagProject}"
        - Key: AMBIENTE
          Value: !Sub "${ParamTagEnv}"
        - Key: CENTRO-COSTO
          Value: !Sub "${ParamTagCostCenter}"
      VersioningConfiguration:
        Status: Enabled
Outputs:
  BucketName:
    Value: !Ref Bucket
  BucketArn:
    Value: !GetAtt Bucket.Arn
  BucketName:
    Value: !GetAtt Bucket.DomainName