AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for creating S3 bucket"
Parameters:
  Versioning:
    Type: "String"
    Default: "Suspended"
    Description: "Versioning [Enabled,Suspended]"
  Environment:
    Type: "String"
    Default: "DEV"
    Description: "Tag of Environment"
  Project:
    Type: "String"
    Default: "PROYECTO-01"
    Description: "Tag name of Project"
  Cost-center:
    Type: "String"
    Default: "PRY01"
    Description: "Tag cost center"
Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub ${BucketNameParam}"
      AccessControl: Private
      VersioningConfiguration: 
        Status: !Ref Versioning
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: "Proyecto"
          Value: !Sub "${ProyectoParam}"
        - Key: "Ambiente"
          Value: !Sub "${AmbienteParam}"
Outputs:
  BucketName:
    Value: !Ref Bucket
  BucketArn:
    Value: !GetAtt Bucket.Arn
  BucketDomainName:
    Value: !GetAtt Bucket.DomainName