AWSTemplateFormatVersion: '2010-09-09'
Description: Template S3 Bucket
Parameters:
  ResourceName:
    Type: String
    Description: The name of the S3 Bucket to create
  Versioning:
    Type: "String"
    Default: "Suspended"
    Description: "Versioning [Enabled,Suspended]"
  ParamTagEnv:
    Type: "String"
    Default: ""
    Description: "Tag of Environment [DEV,UAT,PRD]"
  ParamTagProject:
    Type: "String"
    Default: ""
    Description: "Tag name of Project"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ResourceName}"
      AccessControl: Private
      VersioningConfiguration: 
        Status: !Ref Versioning
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: PROYECTO
          Value: !Sub "${ParamTagProject}"
        - Key: AMBIENTE
          Value: !Sub "${ParamTagEnv}"
      VersioningConfiguration:
        Status: Enabled
